### ISSUE TITLE
Editor: fixed menu should hide when clicking publish

### ISSUE THREAD

**Issue by xiaoniuniu89** [codu-code/codu#505] opened 2023-10-08 20:47 UTC
## Context

We have a fixed menu at the top of our new editor

## Expected Behavior

when user clicks the publish button, the menu should not be visable

## Current Behavior

visable from publish screen

## Screenshots

<img width="1271" alt="Screenshot 2023-10-08 at 21 46 39" src="https://github.com/codu-code/codu/assets/84312595/4f8960c8-675d-4606-9703-937d904c22aa">

## Steps to reproduce

Please provide detailed steps for reproducing the issue

go to alpha/create/new
click publish button

**Comment by John-Paul-Larkin** [comment] 2023-10-09 21:51
Hey Niu. I will try this tomorrow.

**Comment by NiallJoeMaher** [comment] 2023-10-12 20:41
@Fishamble are you taking this one?

**Comment by VickTor61** [comment] 2023-10-15 23:58
Hi @NiallJoeMaher . I will like to contribute to this or fix any other ticket that hasn't been resolved yet

**Comment by John-Paul-Larkin** [comment] 2023-10-16 18:18
Hi Vicktor. I am not working on this, so you can give it a try.

**Comment by vrun1208** [comment] 2023-10-24 11:03
Hi @NiallJoeMaher, looks like the issue is with css, its been a week there is no activity in this issue. If no one is working I can open a PR!

**Comment by NiallJoeMaher** [comment] 2023-10-24 12:28
@VickTor61 are you working on this or can I pass it over to @vrun1208?

**Comment by VickTor61** [comment] 2023-10-24 14:58
@NiallJoeMaher  currently working on it I should make a PR later today

**Comment by VickTor61** [comment] 2023-10-25 04:58
@NiallJoeMaher The error doesn't show in development, Has it already been fixed?
![Screenshot 2023-10-25 at 5 43 03 AM](https://github.com/codu-code/codu/assets/63825684/ac60f441-9157-4eea-b72e-0e489e285090)

**Comment by John-Paul-Larkin** [comment] 2023-10-27 21:16
Hi Vick. You are looking at the wrong editor. 
http://localhost:3000/alpha/new is the url for the alpha editor.
app/alpha/new/[..postidarr]/client.tsx is the component.

**Comment by danboyce92** [comment] 2024-01-02 14:55
Hey there, I have a solution for this problem put together. Could I have this assigned to me so I can create a PR?

**Comment by vrun1208** [comment] 2024-01-02 15:08
I already fixed this issue earlier! @NiallJoeMaher can I open a PR!

**Closed as completed** 2024-10-24 07:05 UTC
