### ISSUE TITLE
Bug: Mobile dropdown menu - not closing

### ISSUE THREAD

**Issue by kera-cudmore** [codu-code/codu#685] opened 2024-01-05 19:32 UTC
## Describe the bug

Dropdown menu stays open on mobile, blocking the page contents when selecting new post, sign in or sign up buttons. Articles, events and support us nav links not affected. Have tried on Chrome and Safari on mobile, seeing the same results on small browser window on desktop too

## To Reproduce
1. Open menu
2. Click new post button OR login button OR sign up button

## Expected behavior

When a menu button is pressed, the menu should close

## Screenshots/Video

https://github.com/codu-code/codu/assets/92253071/5c5cd2f3-a813-489d-b1f7-9f6eaee714bb

## Mobile/Tablet
 - Device: iPhone 13 pro
 - Mobile Browser google chrome & safari

**Comment by John-Paul-Larkin** [comment] 2024-01-16 12:26
Please assign this to me.

**Comment by gdomaradzki** [comment] 2024-03-18 02:39
Couldn't reproduce this on iPhone, nor Chrome (PC). Maybe it was silently fixed?

**Comment by John-Paul-Larkin** [comment] 2024-03-18 09:05
> Couldn't reproduce this on iPhone, nor Chrome (PC). Maybe it was silently fixed?

Hi,
Yes this issue has been fixed.

**Closed as completed** 2024-03-18 09:05 UTC
