### ISSUE TITLE
Article content in light mode is not properly visible.

### ISSUE THREAD

**Issue by abhijeetgurle** [codu-code/codu#554] opened 2023-10-15 17:16 UTC
## Context

After viewing the article in light mode, the text color is not proper due to which users cannot read the articles properly.

## Expected Behavior

The article's content should have darker color.

## Current Behavior

The color of the text inside article is white

## Screenshots

<img width="861" alt="Screenshot 2023-10-15 at 10 43 07 PM" src="https://github.com/codu-code/codu/assets/26840615/60653f9e-06bf-4879-98af-d4075d484b7a">

## Steps to reproduce

Please provide detailed steps for reproducing the issue

1. Go to articles page
2. Click on any article
3. change theme to light mode

## Additional info

Seen this behaviour in develop branch.

**Comment by MadhavKrishanGoswami** [comment] 2023-10-15 18:16
I suppose it is already fixed.

**Comment by NiallJoeMaher** [comment] 2023-10-15 19:02
@abhijeetgurle are you taking this or can @MadhavKrishanGoswami have it? This is already taken? This is a duplicate of #432 so I'm happy if either of you want to take it. 🦾 Just leave a comment on that issue.

**Closed as completed by NiallJoeMaher** 2023-10-15 19:02 UTC
