### ISSUE TITLE
Scroll bug after a draft save is triggered on new post

### ISSUE THREAD

**Issue by gdomaradzki** [codu-code/codu#68] opened 2022-10-15 03:46 UTC
https://www.loom.com/share/2aab0262c3f2400b80281f0b2bcbe892

**Comment by jh3y** [comment] 2022-10-24 09:29
Could you confirm which browser this is in? Thanks for the video 🙏 Makes reproducing way easier when you can see exactly how things are caused.

**Comment by gdomaradzki** [comment] 2022-10-26 07:43
This happened in Chrome Version 106.0.5249.119 (Official Build) (64-bit)

**Comment by NiallJoeMaher** [comment] 2023-02-05 13:14
I haven't been able to reproduce this. 🤔

**Comment by NiallJoeMaher** [comment] 2023-04-07 07:19
Closing because I haven't be able to reproduce this. Feel free to reopen if you can reproduce.

**Closed by NiallJoeMaher** 2023-04-07 07:19 UTC
